export const postActionTypes = {
  FETCH_POSTS_START: "FETCH_POSTS_START",
  FETCH_POSTS_SUCCESS: "FETCH_POSTS_SUCCESS",
  CREATE_POST_START: "CREATE_POST_START",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  SET_ACTIVE_POST: "SET_ACTIVE_POST",
  EDIT_POST_START: "EDIT_POST_START",
  EDIT_POST_SUCCESS: "EDIT_POST_SUCCESS",
  EDIT_POST_FAILED: "EDIT_POST_FAILED",
  DELETE_POST_START: "DELETE_POST_START",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  FETCH_COMMENTS: "FETCH_COMMENTS",
};
